[package]
name = "cryptopals"
version = "0.1.0"
authors = ["Ethan Donowitz <ethowitz@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.4.0"
openssl = "0.10.30"
